# Copyright:	Public domain.
# Filename:	Makefile
# Purpose:	Makefile for Sundial E.
# Contact:	Ron Burkey <info@sandroid.org>.
# Website:	www.ibiblio.org/apollo/index.html
# Mod history:	2019-07-23 RSB	So far we have no source code, so 
#				this is just an empty shell right now.

BASENAME=SundialE

NO_BINSOURCE=yes
EXTRA_YAYUL_ARGS+=--blk2 --early-sbank --parity

include ../Makefile.inc
